version: '3.9'

services:

  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - '${HOME}/Documents/postgres-data:/docker-entrypoint-initdb.d'
      - 'postgres-data:/val/lib/postgresql/data'

volumes:
  postgres-data:


